export const CATEGORY_ALIASES: Record<string, string> = {
    // Snacks
    "snacks": "Snacks",
    "sweet snacks": "Snacks",
    "en:crisps": "Snacks",
    "en:potato-crisps": "Snacks",
    "chips and fries": "Snacks",
    "namkeen": "Snacks",
    "papadum": "Snacks",
    "chips": "Snacks",
    "fr:chips": "Snacks",
    "potato crisps": "Snacks",
    "popcorn": "Snacks",
    "salty snacks": "Snacks",
    "en:appetizers": "Snacks",
    "en:papadum": "Snacks",

    // Biscuits
    "biscuits": "Biscuits",
    "biscuit": "Biscuits",
    "en:biscuits": "Biscuits",
    "cookies": "Biscuits",

    // Beverages
    "beverages": "Beverages",
    "beverages and beverages preparations": "Beverages",
    "beverage preparations": "Beverages",
    "beverage preparation": "Beverages",
    "beverage": "Beverages",
    "drink": "Beverages",
    "en:sodas": "Beverages",
    "boissons et préparations de boissons": "Beverages",
    "boissons": "Beverages",
    "juice": "Beverages",
    "juices and nectars": "Beverages",
    "fruit juices": "Beverages",
    "en:fruit-juices": "Beverages",
    "energy drinks": "Beverages",
    "waters": "Beverages",
    "water": "Beverages",
    "coconut waters": "Beverages",

    // Teas & Coffee
    "teas": "Teas",
    "teas and herbal teas and coffees": "Teas",
    "en:teas": "Teas",
    "tea": "Teas",
    "en:green-teas": "Teas",
    "instant coffees": "Teas",
    "instant coffee": "Teas",
    "en:coffees": "Teas",

    // Dairy
    "dairies": "Dairy",
    "milks": "Dairy",
    "dairy drinks": "Dairy",
    "curd": "Dairy",
    "ghee": "Dairy",
    "whey powder": "Dairy",
    "milk": "Dairy",
    "en:milks": "Dairy",
    "paneer": "Dairy",
    "dahi": "Dairy",
    "buttermilks": "Dairy",
    "produits laitiers": "Dairy",
    "dairy desserts": "Dairy",
    "flavoured milks": "Dairy",
    "cheese": "Dairy",
    "cheese spreads": "Dairy",
    "milkshakes": "Dairy",
    "yogurts": "Dairy",

    // Plant-based
    "plant-based foods and beverages": "Plant-based Foods",
    "plant-based-foods-and-beverages": "Plant-based Foods",
    "aliments et boissons à base de végétaux": "Plant-based Foods",
    "alimentos y bebidas de origen vegetal": "Plant-based Foods",
    "plant-based foods": "Plant-based Foods",
    "soy protein textured rehydrated from soy flour": "Plant-based Foods",

    // Breads
    "breakfasts": "Breakfasts",
    "breads": "Breads",
    "bread": "Breads",
    "en:breads": "Breads",
    "rusks": "Breads",
    "toasts": "Breads",
    "bakery products": "Breads",
    "idly batter mixes": "Breads",
    "dosa batter mixes": "Breads",

    // Condiments & Spices
    "condiments": "Condiments",
    "mixtures of herbs and spices": "Condiments",
    "spice mix": "Condiments",
    "sauces": "Condiments",
    "tomato ketchup": "Condiments",
    "ketchup": "Condiments",
    "en:ketchup": "Condiments",
    "chutneys": "Condiments",
    "chutney": "Condiments",
    "pickles": "Condiments",
    "pickle": "Condiments",
    "tomato sauces": "Condiments",
    "soy sauces": "Condiments",
    "spreads": "Condiments",
    "mayonnaises": "Condiments",
    "cooking helpers": "Condiments",
    "kitchen helpers": "Condiments",
    "masala": "Condiments",
    "spices": "Condiments",
    "en:spices": "Condiments",
    "herbs and spices": "Condiments",
    "turmeric powder": "Condiments",
    "chilli": "Condiments",
    "asafoetida": "Condiments",
    "salt": "Condiments",
    "sugar": "Condiments",
    "jaggery": "Condiments",
    "honey": "Condiments",
    "honeys": "Condiments",
    "en:honeys": "Condiments",
    "syrups": "Condiments",
    "sweeteners": "Condiments",
    "sweet spreads": "Condiments",
    "plant-based spreads": "Condiments",

    // Noodles
    "noodles": "Noodles",
    "instant noodles": "Noodles",
    "en:instant-noodles": "Noodles",
    "en:pastas": "Noodles",
    "wheat vermicelli": "Noodles",

    // Nuts & Dried Fruits
    "cashew nuts": "Nuts & Dried Fruits",
    "dates": "Nuts & Dried Fruits",
    "peanut butters": "Nuts & Dried Fruits",
    "peanut butter": "Nuts & Dried Fruits",
    "peanuts": "Nuts & Dried Fruits",
    "almonds": "Nuts & Dried Fruits",
    "raisins": "Nuts & Dried Fruits",
    "dry fruits": "Nuts & Dried Fruits",
    "nuts": "Nuts & Dried Fruits",
    "pumpkin seeds": "Nuts & Dried Fruits",
    "sunflower seeds": "Nuts & Dried Fruits",
    "chia": "Nuts & Dried Fruits",
    "flax seeds": "Nuts & Dried Fruits",
    "seeds": "Nuts & Dried Fruits",
    "fennel seeds": "Nuts & Dried Fruits",
    "nuts and their products": "Nuts & Dried Fruits",
    "oilseed purees": "Nuts & Dried Fruits",
    "legume butters": "Nuts & Dried Fruits",

    // Chocolate & Confectionery
    "chocolate": "Chocolate",
    "chocolates": "Chocolate",
    "en:chocolates": "Chocolate",
    "chocolate bars": "Chocolate",
    "candy chocolate bars": "Chocolate",
    "milk chocolate bar": "Chocolate",
    "en:chocolate-biscuits": "Chocolate",
    "en:chocolate-candies": "Chocolate",
    "cocoa and its products": "Chocolate",
    "confectioneries": "Confectionery",
    "en:confectioneries": "Confectionery",
    "biscuit (cookie) snack w chocolate filling": "Confectionery",
    "candies": "Confectionery",
    "en:candies": "Confectionery",
    "candy": "Confectionery",
    "sweets": "Confectionery",
    "wafers": "Confectionery",
    "peanut bars": "Confectionery",
    "bars": "Confectionery",
    "en:bars": "Confectionery",

    // Desserts
    "cakes": "Desserts",
    "cake": "Desserts",
    "desserts": "Desserts",
    "ice creams": "Desserts",
    "ice cream": "Desserts",
    "ice cream bars": "Desserts",
    "mueslis": "Desserts",
    "frozen desserts": "Desserts",
    "ice creams and sorbets": "Desserts",

    // Breakfasts & Cereals
    "oats": "Breakfasts",
    "oat": "Breakfasts",
    "breakfast cereals": "Breakfasts",
    "en:breakfast-cereals": "Breakfasts",
    "corn flakes": "Breakfasts",
    "makhana": "Breakfasts",
    "petit-déjeuners": "Breakfasts",
    "poha": "Breakfasts",
    "cereals and potatoes": "Breakfasts",
    "cereals and their products": "Breakfasts",

    // Oils & Fats
    "fats": "Oils & Fats",
    "oil": "Oils & Fats",
    "oils": "Oils & Fats",
    "sunflower oils": "Oils & Fats",
    "coconut oils": "Oils & Fats",
    "soybean oils": "Oils & Fats",
    "olive oils": "Oils & Fats",
    "vegetable fats": "Oils & Fats",
    "vegetable oils": "Oils & Fats",

    // Dietary Supplements
    "dietary supplements": "Dietary Supplements",
    "en:dietary-supplements": "Dietary Supplements",
    "protein powders": "Dietary Supplements",
    "protein bars": "Dietary Supplements",
    "protein bar": "Dietary Supplements",
    "protein shakes": "Dietary Supplements",
    "creatine": "Dietary Supplements",
    "food additives": "Dietary Supplements",
    "bodybuilding supplements": "Dietary Supplements",

    // Pulses & Grains
    "pulses": "Pulses & Grains",
    "masoor dal": "Pulses & Grains",
    "moong dal": "Pulses & Grains",
    "chana dal": "Pulses & Grains",
    "urad dal": "Pulses & Grains",
    "rajma": "Pulses & Grains",
    "chickpeas": "Pulses & Grains",
    "besan": "Pulses & Grains",
    "atta": "Pulses & Grains",
    "maida": "Pulses & Grains",
    "ragi": "Pulses & Grains",
    "tapioca": "Pulses & Grains",
    "flours": "Pulses & Grains",
    "legumes and their products": "Pulses & Grains",
    "legumes": "Pulses & Grains",
    "cereal grains": "Pulses & Grains",

    // Meals
    "meals": "Meals",
    "frozen foods": "Meals",
    "eggs": "Meals",
    "tofu": "Meals",
    "seafood": "Meals",
    "meats and their products": "Meals",

    // Vegetables & Fruits
    "vegetables": "Vegetables & Fruits",
    "fruits": "Vegetables & Fruits",
    "farming products": "Vegetables & Fruits",
    "fruits and vegetables based foods": "Vegetables & Fruits",
    "fruits based foods": "Vegetables & Fruits",

    // Baby food
    "baby foods": "Baby Foods",

    // Personal Care
    "toothpastes": "Personal Care",
    "deodorants": "Personal Care",
    "sunscreen": "Personal Care",
    "soap": "Personal Care",
    "soaps": "Personal Care",
    "handwash": "Personal Care",
    "body gels": "Personal Care",
    "men perfumes": "Personal Care",
    "perfumes": "Personal Care",
    "hair care": "Personal Care",
    "cosmetic products": "Personal Care",

    // Beauty
    "open beauty facts": "Beauty",
    "en:open-beauty-facts": "Beauty",

    // Non-food
    "non food products": "Non-food Products",
    "non-food-products": "Non-food Products",
    "electronic-products": "Non-food Products",
    "household chemicals": "Non-food Products",
    "non alimentaire": "Non-food Products",
    "produtos não alimentares": "Non-food Products",
    "incorrect product type": "Non-food Products",

    // Uncategorized
    "open products facts": "Uncategorized",
    "food": "Uncategorized",
    "books": "Uncategorized",
};
